name:                kldiv
version:             0.1.0.0
github:              "tycho01/kldiv"
license:             BSD3
author:              "Tycho Grouwstra"
maintainer:          "tychogrouwstra@gmail.com"
copyright:           "Copyright (c) 2018 Tycho Grouwstra"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tycho01/kldiv#readme>

dependencies:
- base >= 4.7 && < 5
- integration

library:
  source-dirs: src

tests:
  kldiv-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - kldiv

